# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.191.1/containers/ubuntu/.devcontainer/base.Dockerfile

# [Choice] Ubuntu version: bionic, focal
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04


# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
RUN apt-get update && \
    apt-get -y upgrade && apt-get install make && \
    wget https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/cdf38_0-dist-cdf.tar.gz && \
    tar zxvpf cdf38_0-dist-cdf.tar.gz && rm cdf38_0-dist-cdf.tar.gz && \
    apt-get -y install libncurses5-dev && \ 
    apt-get -y install gcc && \
    cd /cdf38_0-dist && \ 
    make OS=linux ENV=gnu all && \
    sudo make install && \
    apt-get -y install gfortran && \
    apt-get -y install python3-dev python3-h5py python3-matplotlib python3-networkx python3-numpy python3-scipy python3-pip && \
    pip install --upgrade spacepy

# cd cdf38_0-dist && make install 